### ISSUE TITLE
unable to uglify on prod server

### ISSUE THREAD

**Issue by volarname** [khofaai/kh-dropify#1]
> ERROR in static/js/vendor.c58324132e6c9f252b2b.js from UglifyJs Unexpected token: name (i) [./~/vue-dropify/dist/vue-dropify.common.js:454,0][static/js/vendor.c58324132e6c9f252b2b.js:66748,6]

**Comment by akiyamaSM** [comment]
Would you please provide how to reproduce the problem.
Thanks in advance.
